VIA_ENABLE = yes
VIAL_ENABLE = no
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
LTO_ENABLE = no

# DISABLE THESE TO SAVE FIRMWARE SPACE
COMBO_ENABLE = no
TAP_DANCE_ENABLE = no
KEY_OVERRIDE_ENABLE = no

